# Copyright (C) 2024 quip.network
# SPDX-License-Identifier: AGPL-3.0-or-later

stages:
  - test

variables:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_WARN_SCRIPT_LOCATION: "0"

.test_template: &test_template
  stage: test
  image: python:3.11
  before_script:
    - python -m pip install --upgrade pip

pure-python:
  <<: *test_template
  variables:
    HASHSIGS_BUILD_RUST: "0"
  before_script:
    - python -m pip install --upgrade pip
    - pip install -e .[dev]
    - pip install pycryptodome
  script:
    - flake8 .
    - ruff check .
    - mypy hashsigs
    - pytest -q --cov=hashsigs --cov-report=xml:coverage.xml -m "not requires_rust"

rust-backend:
  <<: *test_template
  image: rust:1.82-bullseye
  variables:
    HASHSIGS_BUILD_RUST: "1"
  before_script:
    - apt-get update && apt-get install -y python3 python3-pip
    - python3 -m pip install --upgrade pip
    - python3 -m pip install -v -e .[rust,dev]
    - python3 -m pip install pycryptodome
  script:
    - python3 -c "import hashsigs._rust as m; print('rust ext ok:', m)"
    - python3 -m pytest -q --cov=hashsigs --cov-report=xml:coverage.xml

