# Copyright (C) 2024 quip.network
# SPDX-License-Identifier: AGPL-3.0-or-later

name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  pure-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pycryptodome
      - name: Run lint/type/coverage
        run: |
          pip install flake8 mypy ruff pytest-cov
          flake8 .
          ruff check .
          mypy hashsigs
          pytest -q --cov=hashsigs --cov-report=xml:coverage.xml
      - name: Upload coverage to GitHub (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml

  rust-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: dtolnay/rust-toolchain@stable
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[rust]
          pip install pytest pycryptodome
      - name: Build rust extension
        env:
          HASHSIGS_BUILD_RUST: "1"
        run: |
          python -c "import hashsigs._rust as m; import sys; print('rust ext ok', m)"
      - name: Run tests (rust) with coverage
        env:
          HASHSIGS_BUILD_RUST: "1"
        run: pytest -q --cov=hashsigs --cov-report=xml:coverage.xml
      - name: Upload coverage to GitHub (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-rust-${{ matrix.python-version }}
          path: coverage.xml

